### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by dayron9110** [eyeem/dio_firebase_performance#18]
The last release of this plugin was 0.3.0 but this is not null safety, I need for my project that this plugin to be null safety.

**Comment by ingmferrer** [comment]
I've opened a PR #23, in the meantime you can install this package including my fixes:

in pubspec.yaml
```
  dio_firebase_performance:
    git:
      url: https://github.com/ingmferrer/dio_firebase_performance.git
      ref: master
```
