### ISSUE TITLE
Update firebase_performance to 0.8.0

### ISSUE THREAD

**Issue by ariefwijaya** [eyeem/dio_firebase_performance#21]
I got this error when trying to update firebase_performance: 

Because dio_firebase_performance 0.3.1-dev.3 depends on firebase_performance ^0.7.0 and no versions of dio_firebase_performance match >0.3.1-dev.3 <0.4.0, dio_firebase_performance ^0.3.1-dev.3 requires firebase_performance ^0.7.0.
So, because alia_flutter depends on both dio_firebase_performance ^0.3.1-dev.3 and firebase_performance ^0.8.0+13, version solving failed.
pub get failed (1; So, because alia_flutter depends on both dio_firebase_performance ^0.3.1-dev.3 and firebase_performance ^0.8.0+13, version solving failed.)

**Comment by ingmferrer** [comment]
I've opened a PR #23, in the meantime you can install this package including my fixes:

in pubspec.yaml
```
  dio_firebase_performance:
    git:
      url: https://github.com/ingmferrer/dio_firebase_performance.git
      ref: master
```
