### ISSUE TITLE
Any update planed ? 

### ISSUE THREAD

**Issue by fvisticot** [eyeem/dio_firebase_performance#22]
Can we continue to use this package ? it is still suported ?

**Comment by ingmferrer** [comment]
I've opened a PR #23, in the meantime you can install this package including my fixes:

in pubspec.yaml
```
  dio_firebase_performance:
    git:
      url: https://github.com/ingmferrer/dio_firebase_performance.git
      ref: master
```
