### ISSUE TITLE
Incompatible with firebase_performance: ^0.4.0+1

### ISSUE THREAD

**Issue by passsy** [eyeem/dio_firebase_performance#5]
```yaml
dependencies:
  dio_firebase_performance: ^0.1.0
  firebase_performance: ^0.4.0+1
```

Error
```
Because dio_firebase_performance 0.1.0 depends on firebase_performance ^0.3.1+7 and no versions of dio_firebase_performance match >0.1.0 <0.2.0, dio_firebase_performance ^0.1.0 requires firebase_performance ^0.3.1+7.
So, because my_project depends on both dio_firebase_performance ^0.1.0 and firebase_performance ^0.4.0+1, version solving failed.
pub get failed (1; So, because my_project depends on both dio_firebase_performance ^0.1.0 and firebase_performance ^0.4.0+1, version solving failed.)
```

Please widen the range of firebase_performance to

```yaml
  firebase_performance: ">=0.3.0 <2.0.0"
```
